NixonE/NixonE/Controllers/MyAccountController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NixonE.DAL;
using NixonE.Models;
using NixonE.ViewModels.Acoount;
using NixonE.ViewModels.Basket;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NixonE.Controllers
{
    public class MyAccountController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly NixonDbContext _context;
        public MyAccountController(RoleManager<IdentityRole> roleManager, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager, NixonDbContext context)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }
        public async Task<IActionResult> IndexAsync()
        {

            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login","Account");
            }
            AppUser appUser = await _userManager.Users.FirstOrDefaultAsync(p => p.UserName == User.Identity.Name && !p.IsAdmin);

            AdressVm adressVm = new AdressVm
            {
                Adress = appUser.Adress,
                City = appUser.City,
                ZipCode = appUser.ZipCode,
                Country = appUser.Country
            };

            return View(adressVm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(AdressVm adressVm)
        {
            if (!ModelState.IsValid) return View();
            AppUser userex = await _userManager.GetUserAsync(HttpContext.User);
            userex.City = adressVm.City;
            userex.Country = adressVm.Country;
            userex.ZipCode = adressVm.ZipCode;
            userex.Adress = adressVm.Adress;
            await _userManager.UpdateAsync(userex);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> CheckOut()
        {
            AppUser appUser = await _userManager.Users.FirstOrDefaultAsync(p => p.UserName == User.Identity.Name && !p.IsAdmin);

            string cookieBasket = HttpContext.Request.Cookies["basket"];

            if (!string.IsNullOrWhiteSpace(cookieBasket) && !string.IsNullOrEmpty(cookieBasket) && !(cookieBasket == "[]"))
            {
                List<BasketVM> basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(HttpContext.Request.Cookies["basket"]);
                List<Basket> baskets = new List<Basket>();
                List<Basket> existBasket = await _context.Baskets.Where(b => b.AppUserId == appUser.Id).ToListAsync();
                _context.Baskets.RemoveRange(existBasket);
                foreach (BasketVM basketVM in basketVMs)
                {
                    {
                        Basket basket = new Basket
                        {
                            AppUserId = appUser.Id,
                            ProductId = basketVM.ProductId,
                            ColourId = basketVM.ColorId,
                            Count = basketVM.Count,
                            CreatedAt = DateTime.UtcNow.AddHours(4)
                        };
                        baskets.Add(basket);
                    }
                }

                if (baskets.Count > 0)
                {
                    await _context.Baskets.AddRangeAsync(baskets);
                    await _context.SaveChangesAsync();
                }
            }
            else
            {
                return RedirectToAction("Index","Home");
            }

            if (appUser == null)
            {
                return RedirectToAction("Login", "Account");
            }

            double total = 0;
            List<Basket> basketss = await _context.Baskets.Include(p => p.Product).Include(c => c.Colour).Where(b => b.AppUserId == appUser.Id).ToListAsync();
            List<OrderItem> orderItems = new List<OrderItem>();
            foreach (Basket item in basketss)
            {
                total = total + (item.Count * item.Product.Price);
                OrderItem orderItem = new OrderItem()
                {
                    Count = item.Count,
                    ProductId = item.ProductId,
                    ColourId = item.ColourId,
                    TotalPrice = item.Count * item.Product.Price,
                    CreatedAt = DateTime.UtcNow.AddHours(4),
                    Country = item.Colour.Name

                };
                orderItems.Add(orderItem);
            }

            Order order = new Order()
            {
                Adress = appUser.Adress,
                City = appUser.City,
                Country = appUser.Country,
                ZipCode = appUser.ZipCode,
                AppUserId = appUser.Id,
                CreatedAt = DateTime.UtcNow.AddHours(4),
                TotalPrice = total,
                OrdersItems = orderItems
            };

             _context.Baskets.RemoveRange(basketss);

            HttpContext.Response.Cookies.Append("basket", "");
            await _context.Orders.AddRangeAsync(order);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Home");
        }

        public async Task<IActionResult> GetOrders()
        {
            if(!User.Identity.IsAuthenticated) return RedirectToAction("Login", "Account");
            AppUser appUser = await _userManager.Users.FirstOrDefaultAsync(p => p.UserName == User.Identity.Name && !p.IsAdmin);

            if (appUser == null) return RedirectToAction("Login", "Account");

            List<Order> orders = await _context.Orders.Include(o => o.OrdersItems).ThenInclude(p => p.Product).Include(O => O.AppUser).Where(o=>o.AppUserId == appUser.Id).ToListAsync();

            return View(orders);
        }
    }
}

NixonE/NixonE/Views/MyAccount/GetOrders.cshtml
@model List<Order>
@{
    ViewData["Title"] = "GetOrders";
    int count = 0;
}

<main role="main" id="myAccountMain">
    <div class="layout-main-content">
        <div class="layout-content-wrapper">
            <div class="container">
                <div class="row flex-column-reverse flex-lg-row">
                    <div class="account-sidebar offset-xxl-1 col-xxl-2 col-lg-3">
                        <div class="account-sidebar_content">
                            <h5 class="account-sidebar_title mt-2 mt-lg-5 mb-lg-5">
                                Account
                            </h5>
                            <ul class="account-sidebar_menu">
                                <li class="is-active">
                                    <a asp-controller="MyAccount" asp-action="GetOrders" id="OrderHistoryss">
                                        Order History
                                    </a>
                                </li>
                                <li>
                                    <a asp-controller="MyAccount" asp-action="Index" id="AcDetails">
                                        Account Details
                                    </a>
                                </li>
                                <li>
                                    <a asp-controller="Account" asp-action="LogOut">
                                        Sign out
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="mt-5 account-content col-xxl-8 col-lg-9">
                        <div id="RecoverPasswordFormAccount" class="recover_password hide">
                            <h2>
                                Reset your password
                            </h2>
                            <div class="row">
                                <div class="col-md-6 col-lg-5 col-xl-4">
                                    <div class="p2">
                                        <p>
                                            We will send you an email to reset your password.
                                        </p>
                                    </div>
                                    <form method="post">
                                        <div class="form-group">
                                            <label for="RecoverEmail" class="label-inline">
                                                Email
                                            </label>
                                            <input type="email" id="RecoverEmail" class="form-control">
                                        </div>
                                        <div class="form-group cancel-btn">
                                            <input type="submit" value="Submit" class="btn btn-dark signIn-btn">
                                            <a class="mt-3 p3 text-dark form-text btn-links" href="javascript:void(0)" id="HideRecoverPasswordLinkAccount">
                                                Cancel
                                            </a>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="account-content_main">
                        </div>
                        <div id="orderHis">
                            <h5 class="col-12 pb-2 pl-lg-0 text-lg-left">
                                <a asp-controller="MyAccount" asp-action="GetOrders"></a>
                                Order History
                            </h5>
                            <hr>
                            <div class="account-block">
                                @if (Model.Count() > 0)
                                {
                                    <table class="table table-dark">
                                        <thead>
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">User Name</th>
                                                <th scope="col">Total</th>
                                                <th scope="col">Order Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            @foreach (Order item in Model)
                                            {
                                                count++;
                                                <tr>
                                                    <th scope="row">@count</th>
                                                    <td>@item.AppUser.UserName</td>
                                                    <td>@item.OrdersItems.Sum(o => o.TotalPrice)</td>
                                                    <td>@item.Status</td>
                                                </tr>
                                            }

                                        </tbody>
                                    </table>
                                }
                                else
                                {
                                    <div class="account-block_content">
                                        You haven't placed any orders yet.
                                    </div>
                                }

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

NixonE/NixonE/Views/MyAccount/Index.cshtml
@model AdressVm
@using Microsoft.AspNetCore.Identity
@inject UserManager<AppUser> userManager
@{
    AppUser appUser = null;
    if (User.Identity.IsAuthenticated)
    {
        appUser = userManager.Users.FirstOrDefault(a => a.UserName == User.Identity.Name && !a.IsAdmin);
    }
}
@{
    ViewData["Title"] = "My Account";
}

<main role="main" id="myAccountMain">
    <div class="layout-main-content">
        <div class="layout-content-wrapper">
            <div class="container">
                <div class="row flex-column-reverse flex-lg-row">
                    <div class="account-sidebar offset-xxl-1 col-xxl-2 col-lg-3">
                        <div class="account-sidebar_content">
                            <h5 class="account-sidebar_title mt-2 mt-lg-5 mb-lg-5">
                                Account
                            </h5>
                            <ul class="account-sidebar_menu">
                                <li>
                                    <a asp-controller="MyAccount" asp-action="GetOrders" id="OrderHistor">
                                        Order History
                                    </a>
                                </li>
                                <li class="is-active">
                                    <a asp-controller="MyAccount" asp-action="Index" id="AcDetails">
                                        Account Details
                                    </a>
                                </li>
                                <li>
                                    <a asp-controller="Account" asp-action="LogOut">
                                        Sign out
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="mt-5 account-content col-xxl-8 col-lg-9">
                        <div id="RecoverPasswordFormAccount" class="recover_password hide">
                            <h2>
                                Reset your password
                            </h2>
                            <div class="row">
                                <div class="col-md-6 col-lg-5 col-xl-4">
                                    <div class="p2">
                                        <p>
                                            We will send you an email to reset your password.
                                        </p>
                                    </div>
                                    <form method="post">
                                        <div class="form-group">
                                            <label for="RecoverEmail" class="label-inline">
                                                Email
                                            </label>
                                            <input type="email" id="RecoverEmail" class="form-control">
                                        </div>
                                        <div class="form-group cancel-btn">
                                            <input type="submit" value="Submit" class="btn btn-dark signIn-btn">
                                            <a class="mt-3 p3 text-dark form-text btn-links" href="javascript:void(0)" id="HideRecoverPasswordLinkAccount">
                                                Cancel
                                            </a>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="account-content_main">
                            <div id="acount-main-info" class="row">
                                <h5 class="mb-lg-5 text-lg-left">
                                    Welcome, @User.Identity.Name!
                                </h5>
                                <div class="col-md-12 pl-lg-0">
                                    <div class="account-block mb-5">
                                        <div class="account-block_content">
                                            @appUser.Email
                                        </div>
                                    </div>
                                    <div class="account-block mb-4">
                                        <h6 class="account-block_title">
                                            Shipping Addresses
                                        </h6>
                                        <hr>
                                        <div class="account-block_content">
                                            <address>
                                                @appUser?.FullName
                                                <br>
                                                @appUser?.Country
                                            </address>
                                            <a id="EditAdressShow" class="btn-links py-2" href="#">
                                                Edit
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div id="EditAdress" class="hide">
                                <form method="post">
                                    <h5>
                                        Edit address
                                    </h5>
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <div class="inputs">
                                        <div class="form-group">
                                            <label class="label-inline" asp-for="Adress">Address</label>
                                            <input id="AdressAdress1" asp-for="Adress" class="form-control">
                                            <span class="text-danger" asp-validation-for="Adress"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="label-inline" asp-for="City">City</label>
                                            <input id="AdressCity" asp-for="City" class="form-control">
                                            <span class="text-danger" asp-validation-for="City"></span>
                                        </div>
                                        <div class="form-group">
                                            <label class="label-inline" asp-for="Country">Country/region</label>
                                            <select id="AdressCountry" asp-for="Country" class="form-select" value="">
                                                <option value="Azerbaijan" selected>Azerbaijan</option>
                                                <option value="Afghanistan">Afghanistan</option>
                                                <option value="Albania">Albania</option>
                                                <option value="Algeria">Algeria</option>
                                                <option value="Andorra">Andorra</option>
                                                <option value="Angola">Angola</option>
                                                <option value="Anguilla">Anguilla</option>
                                                <option value="Antigua">Antigua &amp; Barbuda</option>
                                                <option value="Argentina">Argentina</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label class="label-inline" asp-for="ZipCode">ZIP code</label>
                                            <input id="AdressZip" asp-for="ZipCode" class="form-control">
                                            <span class="text-danger" asp-validation-for="ZipCode"></span>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-dark">Save</button>
                                </form>
                                <div class="form-group d-flex align-items-center justify-content-between">
                                    <a id="hideEditAdress" class="p3 float-right btn-links" href="#">
                                        Cancel
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div id="orderHis" class="hide">
                            <h5 class="col-12 pb-2 pl-lg-0 text-lg-left">
                                <a asp-controller="MyAccount" asp-action="GetOrders"></a>
                                Order History
                            </h5>
                            <hr>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>