NixonE/NixonE/Areas/Admin/Controllers/ColorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NixonE.DAL;
using NixonE.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace NixonE.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "SuperAdmin,Admin")]
    public class ColorController : Controller
    {
        private readonly NixonDbContext _context;
        public ColorController(NixonDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(bool? status, int page = 1)
        {
            IEnumerable<Colour> colours = await _context.Colors
                .Include(t => t.ProductColors)
                .Where(t => status == null || t.IsDeleted == status)
                .OrderByDescending(t => t.CreatedAt)
                .ToListAsync();
            ViewBag.Status = status;
            ViewBag.PageIndex = page;
            ViewBag.PageCount = Math.Ceiling((double)colours.Count() / 5);

            return View(colours.Skip((page - 1) * 5).Take(5));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Colour colour)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (string.IsNullOrWhiteSpace(colour.Name))
            {
                ModelState.AddModelError("Name", "Bosluq Olmamalidir");
                return View();
            }

            if (!Regex.IsMatch(colour.Name, @"^[a-zA-Z /&-]+$"))
            {
                ModelState.AddModelError("Name", "Yalniz herif ola biler");
                return View();
            }

            if (await _context.Colors.AnyAsync(s => s.Name.ToLower() == colour.Name.ToLower()))
            {
                ModelState.AddModelError("Name", "Alreade Exists");
                return View();
            }

            colour.CreatedAt = DateTime.UtcNow.AddHours(4);

            await _context.Colors.AddAsync(colour);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Update(int? id)
        {
            if (id == null) return BadRequest();
            Colour colour = await _context.Colors.FirstOrDefaultAsync(s => s.Id == id);
            if (colour == null) return NotFound();
            return View(colour);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, bool? status, Colour colour, int page = 1)
        {
            if (!ModelState.IsValid)
            {
                return View(colour);
            }

            if (id == null) return BadRequest();

            if (id != colour.Id) return NotFound();

            Colour dbcolour = await _context.Colors.FirstOrDefaultAsync(s => s.Id == id);

            if (dbcolour == null) return NotFound();

            if (string.IsNullOrWhiteSpace(colour.Name))
            {
                ModelState.AddModelError("Name", "Bosluq Olmamalidir");
                return View();
            }

            if (!Regex.IsMatch(colour.Name, @"^[a-zA-Z /&-]+$"))
            {
                ModelState.AddModelError("Name", "Yalniz herif ola biler");
                return View();
            }

            if (await _context.Colors.AnyAsync(s => s.Name.ToLower() == colour.Name.ToLower() && s.Id != colour.Id))
            {
                ModelState.AddModelError("Name", "Alreade Exists");
                return View();
            }

            dbcolour.Name = colour.Name;
            dbcolour.UpdatedAt = DateTime.UtcNow.AddHours(4);

            await _context.SaveChangesAsync();

            return RedirectToAction("Index", new { status, page });
        }

        public async Task<IActionResult> Delete(int? id, bool? status, int page = 1)
        {
            if (id == null) return BadRequest();

            Colour dbcolour = await _context.Colors.FirstOrDefaultAsync(t => t.Id == id);

            if (dbcolour == null) return NotFound();

            dbcolour.IsDeleted = true;
            dbcolour.DeletedAt = DateTime.UtcNow.AddHours(4);

            await _context.SaveChangesAsync();

            ViewBag.Status = status;

            IEnumerable<Colour> colours = await _context.Colors
                .Include(t => t.ProductColors)
                .Where(t => status != null ? t.IsDeleted == status : true)
                .OrderByDescending(t => t.CreatedAt)
                .ToListAsync();

            ViewBag.PageIndex = page;
            ViewBag.PageCount = Math.Ceiling((double)colours.Count() / 5);

            return PartialView("_ColourPartial", colours.Skip((page - 1) * 5).Take(5));
        }

        public async Task<IActionResult> Restore(int? id, bool? status, int page = 1)
        {
            if (id == null) return BadRequest();

            Colour dbcolour = await _context.Colors.FirstOrDefaultAsync(t => t.Id == id);

            if (dbcolour == null) return NotFound();

            dbcolour.IsDeleted = false;
            dbcolour.DeletedAt = null;

            await _context.SaveChangesAsync();
            ViewBag.Status = status;

            IEnumerable<Colour> colours = await _context.Colors
                .Include(t => t.ProductColors)
                .Where(t => status != null ? t.IsDeleted == status : true)
                .OrderByDescending(t => t.CreatedAt)
                .ToListAsync();

            ViewBag.PageIndex = page;
            ViewBag.PageCount = Math.Ceiling((double)colours.Count() / 5);

            return PartialView("_ColourPartial", colours.Skip((page - 1) * 5).Take(5));
        }
    }
}

NixonE/NixonE/Areas/Admin/Views/Color/Create.cshtml
@model Colour
@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col-lg-6 h3 mb-4 text-gray-800">
        <h1>Product Colour Create</h1>
    </div>
    <div class="col-lg-12 mx-auto">
        <form method="post">
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" placeholder="Enter Product Colour Name">
                <span class="text-danger" asp-validation-for="Name"></span>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

@section Script{
    <partial name="_ValidateFormPartial">
}

NixonE/NixonE/Areas/Admin/Views/Color/Index.cshtml
@model IEnumerable<Colour>
@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-lg-2 h3 mb-4 text-gray-800">
        <h1>Products Colour</h1>
    </div>
    <div class="col-lg-8 h3 mb-4 text-gray-800">
        <form>
            <div class="form-group">
                <label>Status</label>
                <select class="form-control" name="status">
                    @if (ViewBag.Status == null)
                    {
                        <option selected>All</option>
                        <option value="false">Active</option>
                        <option value="true">DeActive</option>
                    }
                    else if (ViewBag.Status == true)
                    {
                        <option>All</option>
                        <option value="false">Active</option>
                        <option value="true" selected>DeActive</option>
                    }
                    else
                    {
                        <option>All</option>
                        <option value="false" selected>Active</option>
                        <option value="true">DeActive</option>
                    }
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Filter</button>
        </form>
    </div>
    <div class="col-lg-2 h3 mb-4 text-gray-800">
        <a asp-controller="Color" asp-action="Create" asp-area="Admin" class="btn btn-primary">Create</a>
    </div>
</div>
<div class="row">
    <div class="col-lg-12 tagTable">
        @await Html.PartialAsync("_ColourPartial", Model)
    </div>
    <div class="col-lg-12">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                @if (ViewBag.PageIndex > 1)
                {
                    <li class="page-item">
                        <a class="page-link" asp-action="index" asp-route-status="@ViewBag.Status" asp-route-page="1" aria-label="Previous">
                            @("<<")
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" asp-action="index" asp-route-status="@ViewBag.Status" asp-route-page="@(ViewBag.PageIndex-1)" aria-label="Previous">
                            @("<")
                        </a>
                    </li>
                    @if (ViewBag.PageIndex == ViewBag.PageCount && ViewBag.PageIndex > 2)
                    {
                        <li class="page-item"><a class="page-link" asp-route-status="@ViewBag.Status" asp-action="index" asp-route-page="@(ViewBag.PageIndex-2)">@(ViewBag.PageIndex-2)</a></li>
                    }
                    <li class="page-item"><a class="page-link" asp-route-status="@ViewBag.Status" asp-action="index" asp-route-page="@(ViewBag.PageIndex-1)">@(ViewBag.PageIndex-1)</a></li>
                }

                <li class="page-item active"><a class="page-link" asp-route-status="@ViewBag.Status" asp-action="index" asp-route-page="@ViewBag.PageIndex">@ViewBag.PageIndex</a></li>

                @if (ViewBag.PageIndex < ViewBag.PageCount)
                {
                    <li class="page-item"><a class="page-link" asp-route-status="@ViewBag.Status" asp-action="index" asp-route-page="@(ViewBag.PageIndex + 1)">@(ViewBag.PageIndex + 1)</a></li>
                    @if (ViewBag.PageIndex == 1 && (ViewBag.PageIndex + 2) < ViewBag.PageCount)
                    {
                        <li class="page-item"><a class="page-link" asp-route-status="@ViewBag.Status" asp-action="index" asp-route-page="@(ViewBag.PageIndex+2)">@(ViewBag.PageIndex+2)</a></li>
                    }
                    <li class="page-item">
                        <a class="page-link" asp-route-status="@ViewBag.Status" asp-route-page="@(ViewBag.PageIndex + 1)" aria-label="Next">
                            @(">")
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" asp-route-status="@ViewBag.Status" asp-action="index" asp-route-page="@ViewBag.PageCount" aria-label="Next">
                            @(">>")
                        </a>
                    </li>
                }
            </ul>
        </nav>
    </div>
</div>

@section Script{
    <script src="~/admin/js/sweetalert2.all.min.js"></script>
    <script src="~/admin/js/Custom.js" asp-append-version="true"></script>
}

@section Style{
    <link href="~/admin/css/sweetalert2.min.css" rel="stylesheet" />
}

NixonE/NixonE/Areas/Admin/Views/Color/Update.cshtml
@model Colour
@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col-lg-6 h3 mb-4 text-gray-800">
        <h1>Product Colour Update</h1>
    </div>
    <div class="col-lg-12 mx-auto">
        <form method="post">
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" placeholder="Enter new Product Colour Name">
                <span class="text-danger" asp-validation-for="Name"></span>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

@section Script{
    <partial name="_ValidateFormPartial">
}